# Generated by Django 3.2.8 on 2021-10-29 21:35

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('area_empresa', models.CharField(blank=True, max_length=10, null=True)),
                ('criado_por', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=500, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('criado_por', models.CharField(blank=True, max_length=10, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/%d/%m/%Y/')),
                ('status_user', models.CharField(blank=True, max_length=100)),
                ('criado_por', models.CharField(blank=True, max_length=10, null=True)),
                ('empresa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
                ('endereco_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.endereco')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/%d/%m/%Y/')),
                ('criado_por', models.CharField(blank=True, max_length=10, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_por', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
                ('proficional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.usuarios')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_1', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_2', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_3', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_4', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_5', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_6', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_7', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_por', models.CharField(blank=True, max_length=10, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.usuarios')),
            ],
        ),
    ]
