# Generated by Django 3.2.8 on 2021-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
