# Generated by Django 3.2.8 on 2021-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usuarios_tipo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dominio',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
