# Generated by Django 3.2.8 on 2021-11-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_usuarios_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_user',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
