# Generated by Django 3.2.8 on 2021-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_usuarios_tipo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='status_user',
            new_name='especialidade_user',
        ),
        migrations.AlterField(
            model_name='servico',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
